wordpress:
  volumes:
    - ./www:/var/www/html
  image: wordpress:latest
  links:
    - wordpress_db:mysql
  ports:
    - 3000:80
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8000:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: root