version: '2'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 3001:80
    volumes:
      - ./php_config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./www:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: wpd_
    links:
      - database:mysql

  database:
    image: mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/docker-entrypoint-initdb.d