version: '2'
services:
  wordpress:
    image: wordpress:latest
    container_name: wpd-wordpress
    ports:
      - 3001:80
    volumes:
      - ./config/php.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./www:/var/www/html
    env_file:
      - config/.env
    links:
      - database:mysql

  database:
    image: mariadb
    container_name: wpd-mariadb
    env_file:
      - config/.env
    volumes:
      - ./data:/docker-entrypoint-initdb.d
